[libraries]

osvvm = { path = "/home/mike/Desktop/work/04_VerificationAdv/.vscode/work/osvvm", files = [
  "lab/osvvm_src/OsvvmContext.vhd",
  "lab/osvvm_src/AlertLogPkg.vhd",
  "lab/osvvm_src/MessagePkg.vhd",
  "lab/osvvm_src/TbUtilPkg.vhd",
  "lab/osvvm_src/TranscriptPkg.vhd",
  "lab/osvvm_src/TextUtilPkg.vhd",
  "lab/osvvm_src/NamePkg.vhd",
  "lab/osvvm_src/RandomBasePkg.vhd",
  "lab/osvvm_src/RandomPkg.vhd",
  "lab/osvvm_src/ScoreboardGenericPkg.vhd",
  "lab/osvvm_src/ScoreboardPkg_int.vhd",
  "lab/osvvm_src/ScoreboardPkg_slv.vhd",
  "lab/osvvm_src/SortListPkg_int.vhd",
  "lab/osvvm_src/MemoryPkg.vhd",
  "lab/osvvm_src/OsvvmGlobalPkg.vhd",
  "lab/osvvm_src/VendorCovApiPkg.vhd",
  "lab/osvvm_src/CoveragePkg.vhd",
  "lab/osvvm_src/ResolutionPkg.vhd"
]}

defaultlib = { path = "/home/mike/Desktop/work/04_VerificationAdv/.vscode/work", files = [
  "lab/src/duv/cas_pkg.vhd",
  "lab/src/duv/cas_func_pkg.vhd",
  "lab/src/tb/tb_cas_pkg.vhd",
  "lab/src/tb/tb_ctrl_entity.vhd",
  "lab/solutions/tb_ctrl_tc_0001.vhd",
  "lab/solutions/tb_ctrl_tc_0002.vhd",
  "lab/solutions/tb_ctrl_tc_0003.vhd",
  "lab/src/duv/spi_store_data_rtl.vhd",
  "lab/src/duv/spi_slave_struct.vhd",
  "lab/src/duv/cmd_status_ctrl_rtl.vhd",
  "lab/src/duv/spi_send_echo_rtl.vhd",
  "lab/src/duv/serial_if_struct.vhd",
  "lab/src/duv/spi_store_cmd_rtl.vhd",
  "lab/src/duv/spi_com_rtl.vhd",
  "lab/src/duv/registers_rtl.vhd",
  "lab/src/duv/rx_frame_fifo_rtl.vhd",
  "lab/src/tb/tb_ctrl_tc_0001.vhd",
  "lab/src/tb/tb_ctrl_tc_0002.vhd",
  "lab/src/tb/tb_ctrl_tc_0003.vhd",
  "lab/src/tb/model_spi_sim.vhd",
  "lab/src/tb/tb_cas_top_struct.vhd",
  "lab/src/tb/clk_rst_sim.vhd"
]}
